<?php


namespace Brackets\Verifications\Commands;


use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class AddAttributesCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'verifications:add-attributes {attributes} {table}';     //    "boolean('login_verify')->default(0)|string('phone_number')->nullable()" users

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Install a brackets/verifications package';

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle(): void
    {
        $this->info('Generating attributes migration');

        $table = $this->argument('table');

        $this->call('make:migration', ['name' => 'add_attributes_to_'. $table .'_table']);

        $this->info('Modifying migration...');

        $this->strReplaceInFile(
            $this->getMigrationFile('add_attributes_to_'. $table .'_table'),
            'up()
    {
        Schema::table(\'users\', function (Blueprint $table) {
            //',
            $this->getAutoGeneratedUp()
        );

        $this->strReplaceInFile(
            $this->getMigrationFile('add_attributes_to_'. $table .'_table'),
            'down()
    {
        Schema::table(\'users\', function (Blueprint $table) {
            //',
            $this->getAutoGeneratedDown()
        );

        $this->call('migrate');

        $this->info('Verification attributes has been successfully generated');
    }

    private function getMigrationFile($migrationSuffix)
    {
        $migrations = File::files(database_path('migrations/'));

        foreach($migrations as $migration) {
            if(Str::contains($migration->getFilename(), $migrationSuffix)) {
                return $migration->getPath() . DIRECTORY_SEPARATOR . $migration->getFilename();
            }
        }

        return null;
    }

    private function strReplaceInFile($fileName, $toReplace, $replaceWith)
    {
        $content = File::get($fileName);

        return File::put($fileName, str_replace($toReplace, $replaceWith, $content));
    }

    private function getAutoGeneratedUp(): string
    {
        $attributes = explode('|', $this->argument('attributes'));
        $content = '';
        $content_prefix = 'up()
    {
        Schema::table(\'users\', function (Blueprint $table) {
        ';

        foreach($attributes as $attribute) {
            $content = $content . '    $table->'. $attribute .';';
        }

        return $content_prefix . $content;
    }

    private function getAutoGeneratedDown(): string
    {
        $attributes = explode('|', $this->argument('attributes'));
        $content = '';
        $content_prefix = 'down()
    {
        Schema::table(\'users\', function (Blueprint $table) {
            $table->dropColumn([';

        foreach($attributes as $key => $attribute) {
            $attribute = explode('\'', $attribute)[1];      //TODO: needs better solution
            $subsuffix = ($key < count($attributes) - 1) ? ', ' : '';
            $content = $content . '\''. $attribute .'\'' . $subsuffix;
        }

        return $content_prefix . $content .']);';
    }
}
